<<<<<<< HEAD
=======
version: '3.8'

>>>>>>> e03ce5d4a7cf4749095a10ab43be224a455572d0
services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: dk_transactions_db
    environment:
      POSTGRES_DB: dk_transactions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dk_network
    restart: unless-stopped

  # Laravel Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dk_transactions_backend
    environment:
      - APP_ENV=production
<<<<<<< HEAD
      - APP_DEBUG=true
=======
      - APP_DEBUG=false
>>>>>>> e03ce5d4a7cf4749095a10ab43be224a455572d0
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=dk_transactions
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres123
<<<<<<< HEAD
    volumes:
      - ./backend:/var/www/html
=======
      - RUN_MIGRATIONS=true
>>>>>>> e03ce5d4a7cf4749095a10ab43be224a455572d0
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - dk_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  dk_network:
<<<<<<< HEAD
    driver: bridge
=======
    driver: bridge
>>>>>>> e03ce5d4a7cf4749095a10ab43be224a455572d0
